CREATE PROCEDURE usp_get_all_event
AS
BEGIN
    SELECT 
        eventID,
        type,
        title,
        price,
        oldPrice,
        classSize, 
        duration,
        lunchProvided, 
        lessonMaterialsProvided, 
        accessToMembership, 
        availableDates,
        time,
        totalParticipants,
        venue,
        picture
    FROM 
        Event;
END;
